#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'idt==0.1.0','console_scripts','get_global_pos'
__requires__ = 'idt==0.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('idt==0.1.0', 'console_scripts', 'get_global_pos')()
    )
